change imput argument of addFiscalResponsibility()
phpackage/siigo-php-sdk pull request #1
Opened 2020-09-09 21:22 UTC by facu-alvarez

imput argument changed from string to array

2020-09-09 21:33 UTC, alejobit requested changes

2020-09-09 21:33 UTC, alejobit commented on src/Model/Account.php
> +        $this->fiscalResponsibilities[] = $fiscalResponsibilityCodes;
Esto no va a funcionar como esperas, estás agregando el arreglo de responsabilidades fiscales como un elemento del arreglo predefinido en la clase.

Mejor agrega otro método "setter" que remplace por completo el arreglo predefinido y dejas este "adder" de helper para agregar elementos extras.

2020-09-09 22:03 UTC, facu-alvarez commented
fijate ahi bro creo que va bien...

2020-09-10 15:03 UTC, alejobit approved these changes

2020-09-10 15:05 UTC, merged